services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true" 
      - "--providers.docker=true"
      - "--providers.file.filename=/dynamic.yml"
      - "--entrypoints.web.address=:80" 
      - "--entrypoints.websecure.address=:443" 
    ports:
      - "80:80"
      - "443:443" 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certs:/certs" 
      - "./dynamic.yml:/dynamic.yml"  


  webA:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"  
      - "traefik.http.routers.webA.rule=Host(`webA.example.local`)"
      - "traefik.http.routers.webA.entrypoints=websecure" 
      - "traefik.http.routers.webA.tls=true"  
    volumes:
      - ./html/webA.html:/usr/share/nginx/html/index.html

  webB:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"  
      - "traefik.http.routers.webB.rule=Host(`webB.example.local`)"
      - "traefik.http.routers.webB.entrypoints=websecure"
      - "traefik.http.routers.webB.tls=true"
    volumes:
      - ./html/webB.html:/usr/share/nginx/html/index.html
